# Generated by Django 4.2.16 on 2024-09-24 20:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DanceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_booking', models.DateField()),
                ('dance_style', models.TextField(choices=[('Ballet', 'Ballet'), ('Hip Hop', 'Hip Hop'), ('Salsa', 'Salsa'), ('Indian classical', 'Indian classical')])),
                ('start_time', models.TimeField(choices=[(datetime.time(9, 0), '9:00am'), (datetime.time(10, 0), '10:00am'), (datetime.time(11, 0), '11:00am'), (datetime.time(12, 0), '12:00pm'), (datetime.time(13, 0), '1:00pm'), (datetime.time(14, 0), '2:00pm'), (datetime.time(15, 0), '3:00pm'), (datetime.time(16, 0), '4:00pm')])),
                ('confirmed', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, max_length=500)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dance_booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_of_booking', 'start_time'],
            },
        ),
    ]
